spring:
  application:
    name: servicio-productos
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
server:
  port: 8090

springdoc:
  api-docs:
    path: /openapi/docs
  swagger-ui:
    path: /openapi